name: "${project.name}"
main: no.atc.floyd.bukkit.tips.TipsPlugin
version: "${project.version}"
website: "${project.url}"
author: FloydATC
description: "${project.description}"

commands:
  tip:
    description: Show a random tip or add a new one
    usage: /<command> [<text>]
