name: TipsPlugin
main: no.atc.osvein.bukkit.tips.TipsPlugin
version: 2.0
website: https://github.com/Ano-Tech-Computers/TelePlugin/tree/v2/master
authors: [FloydATC, osvein]
description: Give players helpful tips
commands:
  tip:
    description: Show a random tip or add a new one
    usage: |
      /<command> - receive a random tip
      /<command> <text> - add a new tip

permissions:
  tipsplugin.*:
    description: Grants all TipsPlugin permissions
    children:
      tipsplugin.get: true
      tipsplugin.add: true
  tipsplugin.get:
    description: Allows receiving tips
    default: true
  tipsplugin.add:
    description: Allows adding tips
    default: op
      
